volumes:
  jogo_local_postgres_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: jogo_local_django
    container_name: jogo_local_django
    volumes:
      - .:/app:z
    ports:
      - '8000:8000'
    env_file:
      - ./.envs/.postgres
    depends_on:
      - postgres
    command: /start
  
  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: jogo_local_postgres
    container_name: jogo_local_postgres
    volumes:
      - jogo_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres
    ports:
      - '5432:5432'